const SIGN_UP_USER = "users:SIGN_UP_USER"
const SIGN_IN_USER = "users:SIGN_IN_USER"
const UPDATE_PROFILE = "users:UPDATE_PROFILE"
const UPDATE_PASSWORD = "users:UPDATE_PASSWORD"
const FORGET_PASSWORD = "users:FORGET_PASSWORD"
const BLOCK_USER = "users:BLOCK_USER"
const DEACTIVATE_ACCOUNT = "users:DEACTIVATE_ACCOUNT"
const GET_ALL_USERS = "users:GET_ALL_USERS"



module.exports ={
    SIGN_UP_USER,
    SIGN_IN_USER,
    UPDATE_PROFILE,
    UPDATE_PASSWORD,
    FORGET_PASSWORD,
    BLOCK_USER,
    DEACTIVATE_ACCOUNT,
    GET_ALL_USERS
}